//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace WinPart.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("WinPart.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uint16   Availability
        ///uint32   BytesPerSector
        ///uint16   Capabilities[]
        ///string   CapabilityDescriptions[]
        ///string   Caption
        ///string   CompressionMethod
        ///uint32   ConfigManagerErrorCode
        ///boolean  ConfigManagerUserConfig
        ///string   CreationClassName
        ///uint64   DefaultBlockSize
        ///string   Description
        ///string   DeviceID
        ///boolean  ErrorCleared
        ///string   ErrorDescription
        ///string   ErrorMethodology
        ///string   FirmwareRevision
        ///uint32   Index
        ///datetime InstallDate
        ///string   InterfaceType
        ///uint32   LastErrorCode
        ///strin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uint16   Access
        ///uint16   Availability
        ///uint64   BlockSize
        ///string   Caption
        ///boolean  Compressed
        ///uint32   ConfigManagerErrorCode
        ///boolean  ConfigManagerUserConfig
        ///string   CreationClassName
        ///string   Description
        ///string   DeviceID
        ///uint32   DriveType
        ///boolean  ErrorCleared
        ///string   ErrorDescription
        ///string   ErrorMethodology
        ///string   FileSystem
        ///uint64   FreeSpace
        ///datetime InstallDate
        ///uint32   LastErrorCode
        ///uint32   MaximumComponentLength
        ///uint32   MediaType
        ///string   Name
        ///uint64   NumberOfBlocks
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LogicalDrive {
            get {
                return ResourceManager.GetString("LogicalDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unit16   AdditionalAvailability
        ///uint16   Availability
        ///uint16   PowerManagementCapabilities[]
        ///string   IdentifyingDescriptions[1]
        ///uint64   MaxQuiesceTime
        ///uint64   OtherIdentifyingInfo
        ///uint16   StatusInfo
        ///uint64   PowerOnHours
        ///uint64   TotalPowerOnHours
        ///uint16   Access
        ///uint64   BlockSize
        ///boolean  Bootable
        ///boolean  BootPartition
        ///string.  Caption
        ///uint32   ConfigManagerErrorCode
        ///boolean  ConfigManagerUserConfig
        ///string.  CreationClassName
        ///string   Description
        ///string   DeviceID
        ///uint32   DiskInde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Partition {
            get {
                return ResourceManager.GetString("Partition", resourceCulture);
            }
        }
    }
}
